name: Update Frontmatter

on:
  push:
    paths:
      - 'content/docs/**/*.md'

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Get list of modified markdown files
      id: getfile
      run: |
        echo "::set-output name=markdownfiles::$(git diff-tree --no-commit-id --name-only -r HEAD | grep '^content/docs/.*\.md$')"
        
    - name: Run update script if there are markdown changes
      run: |
        if [[ -n "${{ steps.getfile.outputs.markdownfiles }}" ]]; then
          node src/scripts/update-frontmatter.js ${{ steps.getfile.outputs.markdownfiles }}
        fi

    - name: Commit changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        export HUSKY=0
        git add -A
        git commit -m "chore(docs): Update frontmatter date"
        git push
